//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStrumien")]
    public interface IStrumien {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrumien/getStream", ReplyAction="http://tempuri.org/IStrumien/getStreamResponse")]
        System.IO.Stream getStream(string nazwa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrumien/getStream", ReplyAction="http://tempuri.org/IStrumien/getStreamResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> getStreamAsync(string nazwa);
        
        // CODEGEN: Generating message contract since the wrapper name (RequestFileMessage) of message RequestFileMessage does not match the default value (getMStream)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrumien/getMStream", ReplyAction="http://tempuri.org/IStrumien/getMStreamResponse")]
        StreamClient.ServiceReference1.ResponseFileMessage getMStream(StreamClient.ServiceReference1.RequestFileMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStrumien/getMStream", ReplyAction="http://tempuri.org/IStrumien/getMStreamResponse")]
        System.Threading.Tasks.Task<StreamClient.ServiceReference1.ResponseFileMessage> getMStreamAsync(StreamClient.ServiceReference1.RequestFileMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestFileMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RequestFileMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nazwa1;
        
        public RequestFileMessage() {
        }
        
        public RequestFileMessage(string nazwa1) {
            this.nazwa1 = nazwa1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResponseFileMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ResponseFileMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string nazwa2;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public long rozmiar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream dane;
        
        public ResponseFileMessage() {
        }
        
        public ResponseFileMessage(string nazwa2, long rozmiar, System.IO.Stream dane) {
            this.nazwa2 = nazwa2;
            this.rozmiar = rozmiar;
            this.dane = dane;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStrumienChannel : StreamClient.ServiceReference1.IStrumien, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StrumienClient : System.ServiceModel.ClientBase<StreamClient.ServiceReference1.IStrumien>, StreamClient.ServiceReference1.IStrumien {
        
        public StrumienClient() {
        }
        
        public StrumienClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StrumienClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrumienClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StrumienClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream getStream(string nazwa) {
            return base.Channel.getStream(nazwa);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> getStreamAsync(string nazwa) {
            return base.Channel.getStreamAsync(nazwa);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StreamClient.ServiceReference1.ResponseFileMessage StreamClient.ServiceReference1.IStrumien.getMStream(StreamClient.ServiceReference1.RequestFileMessage request) {
            return base.Channel.getMStream(request);
        }
        
        public string getMStream(string nazwa1, out long rozmiar, out System.IO.Stream dane) {
            StreamClient.ServiceReference1.RequestFileMessage inValue = new StreamClient.ServiceReference1.RequestFileMessage();
            inValue.nazwa1 = nazwa1;
            StreamClient.ServiceReference1.ResponseFileMessage retVal = ((StreamClient.ServiceReference1.IStrumien)(this)).getMStream(inValue);
            rozmiar = retVal.rozmiar;
            dane = retVal.dane;
            return retVal.nazwa2;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StreamClient.ServiceReference1.ResponseFileMessage> StreamClient.ServiceReference1.IStrumien.getMStreamAsync(StreamClient.ServiceReference1.RequestFileMessage request) {
            return base.Channel.getMStreamAsync(request);
        }
        
        public System.Threading.Tasks.Task<StreamClient.ServiceReference1.ResponseFileMessage> getMStreamAsync(string nazwa1) {
            StreamClient.ServiceReference1.RequestFileMessage inValue = new StreamClient.ServiceReference1.RequestFileMessage();
            inValue.nazwa1 = nazwa1;
            return ((StreamClient.ServiceReference1.IStrumien)(this)).getMStreamAsync(inValue);
        }
    }
}
